---
name: Trigger Many Secondary

on:
  workflow_run:
    workflows:
    - Trigger Many
    types:
    - completed

jobs:
  ci:
    name: Continuous Integration
    runs-on:
    - ubuntu-20.04

    steps:
    - name: Show env
      run: |
        env | grep GITHUB | sort -u
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "${GITHUB_CONTEXT}"
